### ISSUE TITLE
Parse error response on 401 status from put api 

### ISSUE THREAD

**Issue by saisantosh** [ApptuitAI/metrics-apptuit#5]
```
INFO: -------------------401---------------------
"java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at ai.apptuit.metrics.client.ApptuitPutClient.consumeResponse(ApptuitPutClient.java:136)
	at ai.apptuit.metrics.client.ApptuitPutClient.put(ApptuitPutClient.java:126)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JoeHitHard** [comment]
Fixed #20
